# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Data 8
description: Foundations of Data Science
author: Data 8 Staff
email: data8@berkeley.edu
baseurl: '/su24' # the subpath of your site, e.g. /blog
url: 'https://www.data8.org' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]
logo: "/data8logo.png"
current_week: 5
links:
  test: "[Slides](https://slides.google.com)"
  hw:
    hw01: "[Homework 01](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&branch=main&urlpath=tree%2Fmaterials-su24%2Fhw%2Fhw01%2Fhw01.ipynb&branch=main)"
    hw02: "[Homework 02](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&branch=main&urlpath=tree%2Fmaterials-su24%2Fhw%2Fhw02%2Fhw02.ipynb&branch=main)"
    hw03: "[Homework 03](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&branch=main&urlpath=tree%2Fmaterials-su24%2Fhw%2Fhw03%2Fhw03.ipynb&branch=main)"
    hw04: "[Homework 04](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&branch=main&urlpath=tree%2Fmaterials-su24%2Fhw%2Fhw04%2Fhw04.ipynb&branch=main)"
    hw05: "[Homework 05](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&branch=main&urlpath=tree%2Fmaterials-su24%2Fhw%2Fhw05%2Fhw05.ipynb&branch=main)"
    hw06: "[Homework 06](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&branch=main&urlpath=tree%2Fmaterials-su24%2Fhw%2Fhw06%2Fhw06.ipynb&branch=main)"
    hw07: "Homework 07"
    hw08: "Homework 08"
    hw09: "Homework 09"
    hw10: "Homework 10"
    hw11: "Homework 11"
    hw12: "Homework 12"
  lab:
    lab01: "[Lab 01](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&branch=main&urlpath=tree%2Fmaterials-su24%2Flab%2Flab01%2Flab01.ipynb)"
    lab02: "[Lab 02](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&branch=main&urlpath=tree%2Fmaterials-su24%2Flab%2Flab02%2Flab02.ipynb)"
    lab03: "[Lab 03](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&branch=main&urlpath=tree%2Fmaterials-su24%2Flab%2Flab03%2Flab03.ipynb&branch=main)"
    lab04: "[Lab 04](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&branch=main&urlpath=tree%2Fmaterials-su24%2Flab%2Flab04%2Flab04.ipynb&branch=main)"
    lab05: "[Lab 05](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&branch=main&urlpath=tree%2Fmaterials-su24%2Flab%2Flab05%2Flab05.ipynb&branch=main)"
    lab06: "[Lab 06](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&branch=main&urlpath=tree%2Fmaterials-su24%2Flab%2Flab06%2Flab06.ipynb&branch=main)"
    lab07: "[Lab 07](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&branch=main&urlpath=tree%2Fmaterials-su24%2Flab%2Flab07%2Flab07.ipynb&branch=main)"
    lab08: "Lab 08"
    lab09: "Lab 09"
    lab10: "Lab 10"
    lab11: "Lab 11"
    lab12: "Lab 12"
    lab13: "Lab 13"
  wksht:
    wksht01: "[Lab 01 Worksheet](https://drive.google.com/file/d/1rWxvOnWo3yMyyIADd1nOjhyt6XRYSWkC/view?usp=sharing)"
    wksht02: "[Lab 02 Worksheet](https://drive.google.com/file/d/1xVJUdeZEOnozkgXjL4Pif5UdZulOiqC3/view?usp=sharing)"
    wksht03: "[Lab 03 Worksheet](https://drive.google.com/file/d/1EeLjc7VEBZ0alFpfXvrrm4TgAkyj5s40/view?usp=sharing)"
    wksht04: "[Lab 04 Worksheet](https://drive.google.com/file/d/1fxnuzHvwF1h2DKF0e1CFadQWLmAeiFQ3/view?usp=sharing)"
    wksht05: "[Lab 05 Worksheet](https://drive.google.com/file/d/1Nrq0_9RFe3h8MR9clBBC1ypexxmv0cn6/view?usp=sharing)"
    wksht06: "[Lab 06 Worksheet](https://drive.google.com/file/d/15a5AtXps8yC0WNccjHRTrdGNFOiKKsC5/view?usp=sharing)"
    wksht07: "[Lab 07 Worksheet](https://drive.google.com/file/d/17FlcFru6OHdGYUUzNDpw_LVN9YNnsgJs/view?usp=sharing)"
    wksht08: "Lab 08 Worksheet"
    wksht09: "Lab 09 Worksheet"
    wksht10: "Lab 10 Worksheet"
    wksht11: "Lab 11 Worksheet"
    wksht12: "Lab 12 Worksheet"
    wksht13: "Lab 13 Worksheet"
  proj:
    proj1: "[Project 1: World Population and Poverty](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&branch=main&urlpath=tree%2Fmaterials-su24%2Fproject%2Fproject1%2Fproject1.ipynb&branch=main)"
    proj2: "Project 2: Classifying Movies"
  lec:
    demo:
      demo01: "&#8226; [Demo](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https://github.com/data-8/materials-su24&urlpath=tree/materials-su24/lec/lec01/lec01.ipynb&branch=main)"
      demo02: ""
      demo03: "&#8226; [Demo](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https://github.com/data-8/materials-su24&urlpath=tree/materials-su24/lec/lec03/lec03.ipynb&branch=main)"
      demo04: "&#8226; [Demo](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https://github.com/data-8/materials-su24&urlpath=tree/materials-su24/lec/lec04/lec04.ipynb&branch=main)"
      demo05: "&#8226; [Demo](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https://github.com/data-8/materials-su24&urlpath=tree/materials-su24/lec/lec05/lec05.ipynb&branch=main)"
      demo06: "&#8226; [Demo](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https://github.com/data-8/materials-su24&urlpath=tree/materials-su24/lec/lec06/lec06.ipynb&branch=main)"
      demo07: "&#8226; [Demo](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https://github.com/data-8/materials-su24&urlpath=tree/materials-su24/lec/lec07/lec07.ipynb&branch=main)"
      demo08: "&#8226; [Demo](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https://github.com/data-8/materials-su24&urlpath=tree/materials-su24/lec/lec08/lec08.ipynb&branch=main)"
      demo09: "&#8226; [Demo](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https://github.com/data-8/materials-su24&urlpath=tree/materials-su24/lec/lec09/lec09.ipynb&branch=main)"
      demo10: "&#8226; [Demo](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https://github.com/data-8/materials-su24&urlpath=tree/materials-su24/lec/lec10/lec10.ipynb&branch=main)"
      demo11: "&#8226; [Demo](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https://github.com/data-8/materials-su24&urlpath=tree/materials-su24/lec/lec11/lec11.ipynb&branch=main)"
      demo12: "&#8226; [Demo](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https://github.com/data-8/materials-su24&urlpath=tree/materials-su24/lec/lec12/lec12.ipynb&branch=main)"
      demo13: "&#8226; [Demo](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https://github.com/data-8/materials-su24&urlpath=tree/materials-su24/lec/lec13/lec13.ipynb&branch=main)"
      demo14: "&#8226; [Demo](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https://github.com/data-8/materials-su24&urlpath=tree/materials-su24/lec/lec14/lec14.ipynb&branch=main)"
      demo15: "&#8226; [Demo](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https://github.com/data-8/materials-su24&urlpath=tree/materials-su24/lec/lec15/lec15.ipynb&branch=main)"
      demo16: ""
      demo17: "&#8226; [Demo](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https://github.com/data-8/materials-su24&urlpath=tree/materials-su24/lec/<demo name lec17/<demo name lec17.ipynb&branch=main)"
      demo18: "&#8226; Demo"
      demo19: "&#8226; Demo"
      demo20: "&#8226; Demo"
      demo21: "&#8226; Demo"
      demo22: "&#8226; Demo"
      demo23: "&#8226; Demo"
      demo24: "&#8226; Demo"
      demo25: "&#8226; Demo"
      demo26: "&#8226; Demo"
      demo27: "&#8226; Demo"
      demo28: "&#8226; Demo"
      demo29: "&#8226; Demo"
      demo30: "&#8226; Demo"
      demo31: "&#8226; Demo"
      demo32: "&#8226; Demo"
      demo33: "&#8226; Demo"
      demo34: "&#8226; Demo"
      demo35: "&#8226; Demo"
      demo36: "&#8226; Demo"
      demo37: "&#8226; Demo"
      demo38: "&#8226; Demo"
      demo39: "&#8226; Demo"
    slides:
      slide01: "[Slides](https://docs.google.com/presentation/d/1i0_Cw3QbkfnODzJFVhsajtejyqZcgJTNgChWKQvOZyE/edit?usp=sharing)"
      slide02: "[Slides](https://docs.google.com/presentation/d/1_lbv0tdhuyV3RmB-Avef7VNjsgcxkakMUqh6MhB3ics/edit?usp=sharing)"
      slide03: "[Slides](https://docs.google.com/presentation/d/1tt29OSKvxEnUwQl2Qrix4bITJSanTwD2-_i4Btg8lzg/edit?usp=sharing)"
      slide04: "[Slides](https://docs.google.com/presentation/d/1xR_YSJ5jRg5QcbKZ-jm4rB74lK4HWeR31CmhU--xaic/edit)"
      slide05: "[Slides](https://docs.google.com/presentation/d/1i4o_uekW0WpE4D9Mb-mouvjBXA2MdHzPimZCZHObHRU/edit?usp=sharing)"
      slide06: "[Slides](https://docs.google.com/presentation/d/1eeGUFry5WLYaT2X_8cwaPOR4jsJr0YHGFZru4st0qC0/edit)"
      slide07: "[Slides](https://docs.google.com/presentation/d/1eOObGQxBbVfh08om20cMkcdjSVxFP857cg3ZwrvV8SE/edit?usp=sharing)"
      slide08: "[Slides](https://docs.google.com/presentation/d/16u6qrpiJ9YNzG-V6zxWPcGQPLMKI1JWOVsOvlLZ83Dc/edit)"
      slide09: "[Slides](https://docs.google.com/presentation/d/1wHHllEsm_WfLTcfnYnoyaAB8BZ4cr0JhZBKNDWPB7rs/edit?usp=sharing)"
      slide10: "[Slides](https://docs.google.com/presentation/d/1eX61Dxo8UxxMjNLdFkRqYB_N2iO3fdYXjhgNlQEKPt0/edit?usp=sharing)"
      slide11: "[Slides](https://docs.google.com/presentation/d/1yGu99syqjsktGBSHJudrtdZUzBgqs14smHZrrH0SGBk/edit?usp=sharing)"
      slide12: "[Slides](https://docs.google.com/presentation/d/1STKx8Ykka9Mym9qmvvFGZGK9FcRfLCY68P5GGEr1yAY/edit?usp=sharing)"
      slide13: "[Slides](https://docs.google.com/presentation/d/17GoYqvzUckr5Gpp5VLrI1pmckp_eN9w9OAceN3vfuUk/edit?usp=sharing)"
      slide14: "[Slides](https://docs.google.com/presentation/d/1Paut6OKMAU3mYpyzBsNFadRPcI19NVbaK2zbnyNtJAc/edit?usp=sharing)"
      slide15: "[Slides](https://docs.google.com/presentation/d/19uNT-w4oRj_KpZFFvI1Qb6ciXfiDHxgJykanl7Fm0r0/edit?usp=sharing)"
      slide16: "[Slides](https://docs.google.com/presentation/d/1EySRAUeQuZBxJpgELPjcZBbMYEGW0UMjMUnB3kjTrng/edit?usp=sharing)"
      slide17: "[Slides](https://docs.google.com/presentation/d/18SDrV2Y-Cg0OFYKPBEXy3InlewMJZ_ukmhuLSpQAY4Q/edit?usp=sharing)"
      slide18: "Slides"
      slide19: "Slides"
      slide20: "Slides"
      slide21: "Slides"
      slide22: "Slides"
      slide23: "Slides"
      slide24: "Slides"
      slide25: "Slides"
      slide26: "Slides"
      slide27: "Slides"
      slide28: "Slides"
      slide29: "Slides"
      slide30: "Slides"
      slide31: "Slides"
      slide32: "Slides"
      slide33: "Slides"
      slide34: "Slides"
      slide35: "Slides"
      slide36: "Slides"
      slide37: "Slides"
      slide38: "Slides"
      slide39: "Slides"

  


# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.3.3
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Textbook:
    - 'https://inferentialthinking.com/chapters/intro.html'
  Feedback Form:
    - 'https://forms.gle/Lkg8N2Uk9GVe5sP46'
  # Ed:
  #   - 'https://edstem.org/us/courses/44018/'

# External navigation links
# nav_external_links:
#   - title: Textbook
#     url: https://inferentialthinking.com/chapters/intro.html
#     hide_icon: true

footer_content:

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      subpath: '/assets/images/'
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

plugins:
  - jekyll-seo-tag
