# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Data 8
description: Foundations of Data Science
author: Data 8 Staff
email: data8@berkeley.edu
baseurl: '/su24' # the subpath of your site, e.g. /blog
url: 'https://www.data8.org' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]
logo: "/data8logo.png"
current_week: 1
links:
  test: "[Slides](https://slides.google.com)"
  hw:
    hw01: ["Homework 01"](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Fhw%2Fhw01%2Fhw01.ipynb&branch=main)
    hw02: ["Homework 02"](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Fhw%2Fhw02%2Fhw02.ipynb&branch=main)
    hw03: ["Homework 03"](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Fhw%2Fhw03%2Fhw03.ipynb&branch=main)
    hw04: ["Homework 04"](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Fhw%2Fhw04%2Fhw04.ipynb&branch=main)
    hw05: ["Homework 05"](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Fhw%2Fhw05%2Fhw05.ipynb&branch=main)
    hw06: ["Homework 06"](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Fhw%2Fhw06%2Fhw06.ipynb&branch=main)
    hw07: "Homework 07"
    hw08: "Homework 08"
    hw09: "Homework 09"
    hw10: "Homework 10"
    hw11: "Homework 11"
    hw12: "Homework 12"
  lab:
    lab01: ["Lab 01](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Flab%2Flab01%2Flab01.ipynb&branch=main)
    lab02: ["Lab 02](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Flab%2Flab02%2Flab02.ipynb&branch=main)
    lab03: ["Lab 03](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Flab%2Flab03%2Flab03.ipynb&branch=main)
    lab04: ["Lab 04](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Flab%2Flab04%2Flab04.ipynb&branch=main)
    lab05: ["Lab 05](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Flab%2Flab05%2Flab05.ipynb&branch=main)
    lab06: ["Lab 06](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Flab%2Flab06%2Flab06.ipynb&branch=main)
    lab07: ["Lab 07](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Flab%2Flab07%2Flab07.ipynb&branch=main)
    lab08: ["Lab 08](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Flab%2Flab08%2Flab08.ipynb&branch=main)
    lab09: ["Lab 09](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Flab%2Flab09%2Flab09.ipynb&branch=main)
    lab10: ["Lab 10](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Flab%2Flab10%2Flab10.ipynb&branch=main)
  wksht:
    lab01: ["Lab 01 Worksheet"](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Flab%2Flab01%2Flab01.ipynb&branch=main)
    lab02: ["Lab 02 Worksheet"](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Flab%2Flab02%2Flab02.ipynb&branch=main)
    lab03: ["Lab 03 Worksheet"](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Flab%2Flab03%2Flab03.ipynb&branch=main)
    lab04: ["Lab 04 Worksheet"](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Flab%2Flab04%2Flab04.ipynb&branch=main)
    lab05: ["Lab 05 Worksheet"](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Flab%2Flab05%2Flab05.ipynb&branch=main)
    lab06: ["Lab 06 Worksheet"](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Flab%2Flab06%2Flab06.ipynb&branch=main)
    lab07: ["Lab 07 Worksheet"](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Flab%2Flab07%2Flab07.ipynb&branch=main)
    lab08: ["Lab 08 Worksheet"](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Flab%2Flab08%2Flab08.ipynb&branch=main)
    lab09: ["Lab 09 Worksheet"](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Flab%2Flab09%2Flab09.ipynb&branch=main)
    lab10: ["Lab 10 Worksheet"](https://data8.datahub.berkeley.edu/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fdata-8%2Fmaterials-su24&urlpath=retro%2Ftree%2Fmaterials-su24%2Fmaterials%2Flab%2Flab10%2Flab10.ipynb&branch=main)
  proj:
    proj1: "Project 1: World Population and Poverty"
    proj2: "Project 2: Climate"
    proj3: "Project 3: Classifying Movies"
  lec:
    demo:
    slides:

  


# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.3.3
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Textbook:
    - 'https://inferentialthinking.com/chapters/intro.html'
  Feedback Form:
    - 'https://forms.gle/Lkg8N2Uk9GVe5sP46'
  # Ed:
  #   - 'https://edstem.org/us/courses/44018/'

# External navigation links
# nav_external_links:
#   - title: Textbook
#     url: https://inferentialthinking.com/chapters/intro.html
#     hide_icon: true

footer_content:

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      subpath: '/assets/images/'
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

plugins:
  - jekyll-seo-tag
