name: Update config in data-8/su24

on:
  push:
    paths:
      - hw/**/*
      - lab/**/*
      - proj/**/*
    branches:
      - main

jobs:
  update-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install PyGithub

      - name: Find new directories and update config.yml
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          python update_config.py